### ISSUE TITLE
New deployment, Narnia of new Fun

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#1894]
https://securityheaders.com/?q=https%3A%2F%2Fkodadot.xyz&followRedirects=on

We've had A back at Netlify, time to fix this stuff again on Cloudflare

From Netlify.toml -- https://github.com/kodadot/nft-gallery/blob/main/netlify.toml
```toml
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Referrer Policy is a new header that allows a site to control how much information the browser includes with navigations away from a document and should be set by all sites.
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Don't load any resource type not explicitly enabled
    # Disable plugins like Flash or Silverlight
    # Load images, scripts, stylesheets and fonts from self
    ## Content-Security-Policy = "upgrade-insecure-requests" <- this did not work tho
    # Prevent browsers from incorrectly detecting non-scripts as scripts
    X-Content-Type-Options = "nosniff"
    # Block site from being framed with X-Frame-Options and CSP
    Content-Security-Policy = "frame-ancestors 'self';"
    # Basic one if one above won't work
    # Content-Security-Policy = "default-src 'self';"
    # For future testing, refer to https://github.com/kodadot/nft-gallery/issues/540
    # Permissions-Policy = "interest-cohort=()"
```

![image](https://user-images.githubusercontent.com/5887929/149797929-761a6b49-9b29-4170-b5e2-8737374735ad.png)

Seems on https://beta.kodadot.xyz it's working well

![image](https://user-images.githubusercontent.com/5887929/149809239-e5ec8dfb-04fc-4f18-a53f-71b8e45b8084.png)
