### ISSUE TITLE
update i18n translate plugin to use Transifex

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2]
Use proper translation management system, so anyone can contribute through transifex or similar systems
- seems vue/cli is using it https://www.transifex.com/vuejs/vue-cli/
we are looking to have various translation focused on Asian countries, in a particular order
- Korean
- Chinese
- japan

**Comment by yangwao** [comment]
Few approaches I've found
- https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-vue-app-with-vue-i18n 
- https://lokalise.com/blog/vue-i18n/
- https://medium.com/hong-kong-tech/dynamic-translate-using-vue-i18n-vuejs-c730093a63e2

- maybe https://www.npmjs.com/package/@wealthbar/i18n ?
- https://www.npmjs.com/package/@transifex/native
- https://www.npmjs.com/package/@transifex/cli

**Comment by roiLeo** [comment]
This one is easy to set up.

You have to : 
1. Create a Transifex account
2. Join or recreate "Kodadot" organisation
3. Follow [these steps](https://docs.transifex.com/transifex-github-integrations/github-tx-ui#linking-a-specific-project-with-a-github-repository) to link github project
4. Edit the Yaml config. Mine is: 
```yaml 
filters:
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: KEYVALUEJSON
    source_language: en
    source_file: src/locales/en.json
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: 'src/locales/<lang>.json'
```
5. Profit.

Some of the locales should be renamed to match the right language.
[Here](https://github.com/roiLeo/nft-gallery/pull/1) you can find an automatic pull request example to see what it looks like.
