### ISSUE TITLE
Automate pushing updates to `beta` branch

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#5770]
I would like to have regular updates going from `main` to `beta` branch with naming which PRs (titles) are being merged there and label it with `beta` label on weekly basis, Tuesday let's say. 

- https://github.com/kodadot/nft-gallery/pull/5769
- https://github.com/kodadot/nft-gallery/pull/5715

This might be helpful
- https://github.com/marketplace/actions/create-pull-request

**Comment by yangwao** [comment]
ooh
- https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action#comment133370436_73340290

```
  steps:
    - name: create pull request
      run: gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
