### ISSUE TITLE
AssetHub Kusama Minting: Where is Classic mint?

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/nft-gallery#7049]
So I'm trying to onboard an artist to mint her collection on AssetHub Kusama, but apparently, we don't have this option anymore. Where is classic minting? It's possible to mint only Waifu or Mass Mint. 

She will be minting on rmrk2 for now. 

## Proof:
<img width="1458" alt="Screenshot 2023-08-30 at 15 42 35" src="https://github.com/kodadot/nft-gallery/assets/104380776/d6d87e13-f69b-449c-bf83-41ba9136618a">

**Comment by roiLeo** [comment]
- related with #5879 & #6538

**Comment by yangwao** [comment]
- #5939 will hopefully fixes this

Till now only iirc massmint works?

**Comment by daiagi** [comment]
I think the code we have for ahp minting should work as is for ahk. It's just never been tested and the dropdown option for classic create is not shown.


I'll verify that and expose the option

**Comment by kodabot** [comment]
ASSIGNED - @daiagi 🔒 LOCKED -> Friday, September 1st 2023, 13:21:17 UTC -> 36 hours

**Comment by yangwao** [comment]
> I think the code we have for ahp minting should work as is for ahk. It's just never been tested and the dropdown option for classic create is not shown.
> 
> I'll verify that and expose the option

yes! thank you!

**Comment by daiagi** [comment]
something up with Kusama asset hub?

transaction params created by us make complete sense:

```yaml
calls:
  - args:
      collection: '109'
      item: '2'
      mint_to:
        Id: DBVPJeM91LawsF8dqphFYmdPwtxfpXqbgBtVaxn41CT3Amn
      witness_data: null
    method: mint
    section: nfts
  - args:
      collection: '109'
      item: '2'
      data: ipfs://ipfs/bafkreid4mbe37fg67rhlhzniruu5xip2vrynftjtmjdcyv6zb56jdmjlwi
    method: setMetadata
    section: nfts
  - args:
      collection: '109'
      item: '2'
      price: 100,000,000,000
      whitelisted_buyer: null
    method: setPrice
    section: nfts
```
but
 1.the tx doesn't move beyond broadcasting
2.does not appear in my [acccout](https://assethub-kusama.subscan.io/account/DBVPJeM91LawsF8dqphFYmdPwtxfpXqbgBtVaxn41CT3Amn)
3.the network last block time is 2 hors ago?!!
    
    
![image](https://github.com/kodadot/nft-gallery/assets/22791238/d242e9db-18d4-413a-ace3-0aedca97035a)
