### ISSUE TITLE
The Generative drop v0

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#7580]
### Context 

In KodaDot we are huge fans of generative and programatic art in KodaDot.

###   From UI perspective 

1. we first need to get drop of type `generative` waiting for #7570

2.   By default image of the art would be shown

3.  When user press run button `image` would change to `iframe` where `src` would be `content` + ?`hash={hash}  `.  **by default hash = accountId**

<img width="400" alt="variations 00" src="https://github.com/kodadot/nft-gallery/assets/22471030/474da28e-4629-4df3-a778-85eb899a8243">

￼
4.   When user clicks variation you create new `hash = encodeAddress(accountId, newss58)`
 where newss58 is number from 0 up to 15000 https://github.com/paritytech/ss58-registry/blob/30889d6c9d332953a6e3333b30513eef89003f64/ss58-registry.json#L1292C17-L1292C22 
 
 > at this step it is highly possible that you will re-mount `iframe` 

5.   When user is satisfied with the iteration he or she creates and iteration 

6.   Metadata are constructed on frontend as follows:

```yml
 name: same as collection
 description: same as collection 
animation_url: content + hash
image: same as collection, wating for https://github.com/kodadot/workers/issues/169
iterationHash: hash
__other to be added
```
